os: linux
dist: trusty
sudo: required
language: python
python:
- '3.6'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- pip install -r requirements.txt
before_install:
- openssl aes-256-cbc -K $encrypted_72242892b593_key -iv $encrypted_72242892b593_iv
  -in config.ini.enc -out scraper/config.ini -d
script:
- make travis
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- mkdir /home/travis/virtualenv/python2.7.12/bin
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser
notifications:
  webhooks:
    urls:
      - https://integrations.bonbotics.io/travis/webhook/n0SFugflXzgKY8Mc7wuQf5vqPj1vPiG8JApYv2YpRqQ
    on_success: always
    on_failure: always
    on_start: never
