os: linux
dist: trusty
sudo: required
language: python
python:
- '3.6'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- pip install -r requirements.txt
before_install:
- openssl aes-256-cbc -K $encrypted_72242892b593_key -iv $encrypted_72242892b593_iv
  -in config.ini.enc -out scraper/config.ini -d
script:
- make travis
