os: linux
dist: trusty
sudo: required
language: python
python:
- '3.6'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- pip install -r requirements.txt
script:
- make travis
before_script:
- wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/bin/
- export CHROME_BIN=chromium-browser
notifications:
  webhooks:
    urls:
    - https://integrations.bonbotics.io/travis/webhook/n0SFugflXzgKY8Mc7wuQf5vqPj1vPiG8JApYv2YpRqQ
    on_success: always
    on_failure: always
    on_start: never
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: appname
  on:
    branch: master
